---
- name: Listen for events on a webhook
  hosts: all

  sources:
    - name: dynatrace_events
      dynatrace.event_driven_ansible.dt_esa_api:
        dt_api_host: "{{ _dyna_api }}"
        dt_api_token: "{{ dyna_token }}"
        delay: 60
        # proxy: "http://my-proxy:3128"

  rules:

    - name: Detectar servicio httpd inactivo
      condition: event.title is match("httpd is in undesirable")
      action:
        run_job_template:
          name: "levanta httpd"
          organization: "Default"

    - name: Problem payload Dynatrace for CPU issue
      condition: event.title is match("CPU saturation")
      action:
        run_job_template:
          name: "dyna-template"
          organization: "Default"

    - name: Update comments in Dynatrace
      condition: event.status == "OPEN"
      action:
        run_job_template:
          name: "dyna-template2"
          organization: "Default"
