---
- name: BGP Change Observation
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Send notification message via Mattermost
      delegate_to: localhost
      community.general.mattermost:
       url: http://rhel02.lab.local:8065
       api_key: "{{ MATTERMOST_API_TOKEN }}"
       attachments:
         - text: "!!!!!! VLAN INFO !!!!!!"
           color: '#ff00dd'
           title: Vlan info
           fields:
            - title: Lista de vlans cisco
              value: "Listado de vlans: {{ vlan-info }}"
              short: true
            

